### ISSUE TITLE
http://127.0.0.1:8000/blog/

### ISSUE THREAD

**Issue by lucasjinreal** [Pei2tech/Django-Puput-Bulma-Blog#1]
![image](https://user-images.githubusercontent.com/21303438/122078978-91cf5180-ce2f-11eb-8662-0f3dfe214a84.png)

run `python manage.py runserver` got this

**Comment by Pei2tech** [comment]
You will get this error as the first time to run  `python manage.py runserver`, because there is no data in the database.  For this issue, I will update the README.md to avoid this confusion.  In order to create the blog, please open your browser at `http://127.0.0.1:8000/cms`  to login the admin page.  After sign-in the admin page, please select the **page** icon and then clicking the **+ ADD CHILD PAGE** button. Because the demo just uses the name _blog_ as default homepage, please input the value _blog_ as the slug for the **PROMOTE** tab.  After editing some fields of **CONTENT** tab, please just click **SAVE DRAFT** and **PUBLISH**,  the correct result of http://127.0.0.1:8000 should be shown as renew it.  If you were not familiar with  Wagtail editor’s dashboard,  I thought it would be helpful to visit [Wagtail Editor’s guide](https://docs.wagtail.io/en/v2.0/editor_manual/index.html "Wagtail Editor’s guide").

**Comment by lucasjinreal** [comment]
I added a page and still can not open this default link

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/122638376-4d410000-d126-11eb-8b23-862e9f9c8be4.png)
![image](https://user-images.githubusercontent.com/21303438/122638378-5205b400-d126-11eb-9d8c-529f9c40b2e0.png)

**Comment by lucasjinreal** [comment]
I can not enter blog (default home), but I can open individual article. However, none of any button can work, can not login or something

![image](https://user-images.githubusercontent.com/21303438/122638545-3fd84580-d127-11eb-9865-1261d6498ed9.png)

**Comment by lucasjinreal** [comment]
Will u consider also add it more complete feature in?

**Comment by Pei2tech** [comment]
The last figure you posted have already entered the blog, so I did not catch your point that "I can not enter blog (default home)".   I didn't implement menu items such as About, Contact ...,  because they should be implemented by yourself.  Anyway, you can modify the file base.html which is in the folder " ../Myblog/blog/templates/puput" to change the menu name as below. 
```html
                <div id="navbarBasicExample" class="navbar-menu">
                     <div class="navbar-end">
                         <div class="navbar-item is-hoverable">
                             <a href="/"> <i class="fa fa-user"></i>
                                 <span style="color: {{blog_page.label_color}}">About</span>
                             </a>
                         </div>
                         <a class="navbar-item" href="">
                             Contact
                         </a>
                         <div class="navbar-item">
                                 <a href="/" class="button is-info">
                                     Login
                                 </a>
                         </div>
                     </div>
               </div>
```

**Comment by Pei2tech** [comment]
The setting I did.  It has some difference from you. 
![blog_setup](https://user-images.githubusercontent.com/26864218/122781030-00098d80-d2e2-11eb-818b-3f9f3796493a.png)

**Comment by Pei2tech** [comment]
The last figure you posted have already entered the blog, so I did not catch your point that "I can not enter blog (default home)".   

I didn't put any link for menu items such as About, Contact ...,  because I thought they should be implemented by yourself.  Anyway, you can modify the file **base.html** which is in the folder  **../Myblog/blog/templates/puput** to change the menu name or add link.  

```html
                <div id="navbarBasicExample" class="navbar-menu">
                     <div class="navbar-end">
                         <div class="navbar-item is-hoverable">
                             <a href="/"> <i class="fa fa-user"></i>
                                 <span style="color: {{blog_page.label_color}}">About</span>
                             </a>
                         </div>
                         <a class="navbar-item" href="">
                             Contact
                         </a>
                         <div class="navbar-item">
                                 <a href="/" class="button is-info">
                                     Login
                                 </a>
                         </div>
                     </div>
               </div>
```

**Comment by lucasjinreal** [comment]
@Pei2tech  I can only enter individual article by press live on that article, but not able to enter blog default home, 127.0.0.1:8000

How did u able to switch to this PROMOTE? Mine is not same as you

**Comment by Pei2tech** [comment]
As what I posted before, I just open the browser at http://127.0.0.1:8000/cms and then sign in the page.   The title of the first page should be **Welcome to the Blog Wagtail CMS**.  Clicking on the **Page** icon and then  **+ ADD CHILD PAGE** button, the PROMOTE tab should be there.   I have tested on windows 10 and Ubuntu 20.04, both of them can enter the default home page.   Did you use the new project or existed project for this?   
Anyway, please use `pip list` to check the version for wagtail and Django. The version of wagtail should be 2.13.x and django should be 3.0.14 .   If both of them are no issue, you may follow the installation and configuration to `git clone ...` to another new folder to try it again.

**Comment by lucasjinreal** [comment]
@Pei2tech  thank u Sir, I am now in

![image](https://user-images.githubusercontent.com/21303438/123121630-e7cb7700-d477-11eb-8109-82fbdb1364f3.png)


But  just wonder will u continue make the site more enhancement such as login and show about page etc?

**Comment by lucasjinreal** [comment]
![image](https://user-images.githubusercontent.com/21303438/123123261-48a77f00-d479-11eb-87fc-3e70aaa81fa0.png)

It could be even more nicer if we can have comments functionality.

**Comment by Pei2tech** [comment]
[Puput](https://puput.readthedocs.io/en/latest/) support for Disqus comments.  You can refer to its [Doc](https://puput.readthedocs.io/en/latest/comments.html).   By the way, if you want to use tags with unicode (ex. chinese), please install **Unidecode**.  
```
(.venv)...$pip install Unidecode
```

**Comment by lucasjinreal** [comment]
@Pei2tech Disqus not supported in Chinese (great fire wall). Does there any plugin or vendor lib can do comments right inside sqlite in wagtail?

**Comment by Pei2tech** [comment]
@jinfagang   There is [wagtailcomments_xtd](https://github.com/adrienlachaize/wagtailcomments_xtd) which merges [django-comments-xtd](https://github.com/danirus/django-comments-xtd) to admin page, but I am not sure whether django-comments-xtd can work with Puput.

**Comment by Pei2tech** [comment]
> But just wonder will u continue make the site more enhancement such as login and show about page etc?

I have considered to use [markdown-view](https://github.com/rgs258/django-markdown-view) to support About page but not try it yet.

**Comment by lucasjinreal** [comment]
@Pei2tech maybe we can have a try on django-comments-xtd, if it can work with django and wagtail, it should work with putput.

**Comment by Pei2tech** [comment]
> @Pei2tech maybe we can have a try on django-comments-xtd, if it can work with django and wagtail, it should work with putput.

This demo is part of [function](https://demo.cmssds.org/bulletin/) for this project [ipatrans](https://demo.cmssds.org) and I need to focus on other core projects, so no more time to add this feature.  If you would like to try it, it would be cool and I can help to check issues.
